            FROM slurm-d

            ARG DEBIAN_FRONTEND=noninteractive
            RUN apt update -y
            RUN apt install munge nano build-essential git wget sudo openssh-server -y

            RUN useradd -m admin -s /usr/bin/bash -d /home/admin && echo "admin:admin" | chpasswd && adduser admin sudo && echo "admin     ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

            RUN echo 'OPTIONS="--force --key-file /etc/munge/munge.key"' > /etc/default/munge

            COPY slurm.conf /etc/slurm/
            #   COPY cgroup.conf /etc/slurm/
            COPY docker-entrypoint.sh /etc/slurm/

            #EXPOSE 6817 6818 6819  

            RUN chmod +x /etc/slurm/docker-entrypoint.sh 

            ENTRYPOINT ["/etc/slurm/docker-entrypoint.sh"]